# COSS Metadata Template v0.0.2
# This is the official COSS (Contriboss Open Source Standard) specification template
# Copy this file to your project root as coss.toml and customize for your project

##########################################################
# 1. Basic Project Information
name = "state_machines-activemodel"
version = "0.31.0"
description = "Adds support for creating state machines for attributes on ActiveModel models"
licenses = ["MIT"]
ai_contributions = true
coss_compliant = true
homepage = "https://github.com/state-machines/state_machines-activemodel"
keywords = [
    "ruby",
    "state-machine",
    "activemodel",
    "rails",
    "validations",
    "callbacks",
]

##########################################################
# 2. Repository and Issue Tracking
repository = "https://github.com/state-machines/state_machines-activemodel"
issue_tracker = "https://github.com/state-machines/state_machines-activemodel/issues"
documentation = "https://github.com/state-machines/state_machines-activemodel/blob/master/README.md"
security_policy = ""

##########################################################
# 3. Languages, Frameworks, and Platforms
languages = ["ruby"]

[frameworks]
rails = "7.1+"
activemodel = "7.1+"

supported_platforms = ["linux", "darwin", "windows"]

##########################################################
# 4. Dependency Lock Files
[dependency_locks]
ruby = "Gemfile.lock"
appraisal = "gemfiles/*.gemfile.lock"

[packaging]
ruby = "gem build state_machines-activemodel.gemspec"

##########################################################
# 5. Maintainers and Governance
maintainers = ["terminale@gmail.com"]
governance = { type = "informal" }

##########################################################
# 6. Linting, Formatting, and Static Analysis
lint = "bundle exec rubocop"
format = "bundle exec rubocop -a"
static_analysis = ["bundle exec rubocop"]

##########################################################
# 7. CI and Build Commands
build = "bundle install"
test = "rake test"
test_all = "appraisal rake test"
coverage = ""

##########################################################
# 8. Tests and Quality Metrics
[test_frameworks]
ruby = "minitest"
appraisal = true  # Tests against multiple Rails versions

test_report_format = "minitest"
coverage_threshold = 0

##########################################################
# 9. Commit Guidelines and Formats
commit_message_format = ""

##########################################################
# 10. Release and Changelog
changelog = "CHANGELOG.md"
release_tag_pattern = "v{version}"

##########################################################
# 11. Badges and Integrations (Optional)
[badges]
ci = "https://github.com/state-machines/state_machines-activemodel/actions/workflows/ruby.yml/badge.svg"
coverage = ""
license_badge = ""

##########################################################
# 12. Optional Miscellaneous Fields
chat = ""
support = { type = "github", contact = "https://github.com/state-machines/state_machines-activemodel/issues" }
apidocs = ""

##########################################################
# 13. Environment and Runtime Info
[environments]
ruby = "3.1+"
rails = "7.1+"

##########################################################
# 15. Project Classification
project_type = "library"
maturity = "stable"
audience = ["developers", "ruby-developers", "rails-developers"]

##########################################################
# 16. Localization / Internationalization
[i18n]
default_locale = "en"
supported_locales = ["en"]
translation_files = "lib/state_machines/integrations/active_model/locale.rb"

##########################################################
# 17. Contribution Automation
[contribution_tooling]
dependabot = false
precommit_hooks = false
ai_review = "disabled"
codeowners = ""

##########################################################
# 18. Security Scanning and SBOM
[security]
sbom = ""
vulnerability_scanner = ""
license_compliance_tool = ""

##########################################################
# 19. Documentation Quality Flags
[docs]
coverage = 0
style = ""
ai_summary_enabled = false

##########################################################
# 20. Submodules and Component References
[dependencies]
# Core dependency
state_machines = ">= 0.31.0"
activemodel = ">= 7.1"

[related_projects]
# Other gems in the state_machines ecosystem
state_machines = "https://github.com/state-machines/state_machines"
state_machines-activerecord = "https://github.com/state-machines/state_machines-activerecord"
state_machines-audit_trail = "https://github.com/state-machines/state_machines-audit_trail"
state_machines-graphviz = "https://github.com/state-machines/state_machines-graphviz"
state_machines-yard = "https://github.com/state-machines/state_machines-yard"

##########################################################
# 21. Integration-Specific Information
[activemodel_integration]
features = [
    "state validations",
    "transition callbacks",
    "dirty attribute tracking",
    "i18n support",
    "mass assignment protection",
    "validation errors on invalid transitions",
]
tested_versions = ["7.1", "7.2", "8.0", "edge"]

##########################################################
# 22. Testing Commands
[testing]
specific_file = "ruby -Itest test/path/to/test.rb"
specific_test = "ruby -Itest test/path/to/test.rb:line_number"
appraisal_setup = "appraisal install"
rails_version_test = "appraisal rails-7-1 rake test"
